//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADO_OOPExample.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detail_transactions
    {
        public string ID { get; set; }
        public string TRANSACTION_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public int QUANTITY { get; set; }
        public int PRICE { get; set; }
    
        public virtual product product { get; set; }
        public virtual transaction transaction { get; set; }
    }
}
